/**
 * Created by erichua on 13/12/2017.
 */
// data generated by http://www.richyli.com/name/index.asp
export default [
  {'searchStr': 'A1'},
  {'searchStr': 'B1'},
  {'searchStr': 'A2'},
  {'searchStr': 'C1'},
  {'searchStr': 'Linder'},
  {'searchStr': 'DoDemon'}
]
